/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'submittedReports' : bigint,
  'totalReports' : bigint,
  'approvedUsers' : bigint,
  'totalUsers' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface DeletedUser {
  'principal' : Principal,
  'profile' : UserProfile,
}
export interface LaporanRencanaKerja {
  'status' : ReportStatus,
  'tanggal' : string,
  'sumberDana' : string,
  'waktuPelaksanaan' : string,
  'volume' : string,
  'author' : Principal,
  'metodeKegiatan' : string,
  'keterangan' : string,
  'lokasiKegiatan' : string,
  'indikatorKeberhasilan' : string,
  'lampiranIds' : Array<string>,
  'nomorLaporan' : string,
  'sasaran' : string,
  'namaKegiatan' : string,
}
export interface LaporanUpdate {
  'status' : ReportStatus,
  'tanggal' : string,
  'sumberDana' : string,
  'waktuPelaksanaan' : string,
  'volume' : string,
  'metodeKegiatan' : string,
  'keterangan' : string,
  'lokasiKegiatan' : string,
  'indikatorKeberhasilan' : string,
  'lampiranIds' : Array<string>,
  'nomorLaporan' : string,
  'sasaran' : string,
  'namaKegiatan' : string,
}
export type ReportStatus = { 'submitted' : null } |
  { 'draft' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'nip' : string,
  'name' : string,
  'role' : UserRole,
  'tandaTangan' : [] | [string],
  'wilayah' : string,
  'unitKerja' : string,
}
export type UserRole = { 'admin' : null } |
  { 'guest' : null } |
  { 'penyuluh_kb' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAttachmentToReport' : ActorMethod<[string, string], undefined>,
  'adminDeleteReport' : ActorMethod<[Principal, string], undefined>,
  'adminDeleteUser' : ActorMethod<[Principal], undefined>,
  'adminEditReport' : ActorMethod<
    [Principal, string, LaporanUpdate],
    undefined
  >,
  'adminEditUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
  'adminRestoreUser' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createReport' : ActorMethod<[LaporanRencanaKerja], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllReports' : ActorMethod<[], Array<LaporanRencanaKerja>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyReports' : ActorMethod<[], Array<LaporanRencanaKerja>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listDeletedUsers' : ActorMethod<[], Array<DeletedUser>>,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'removeAttachmentFromReport' : ActorMethod<[string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitReport' : ActorMethod<[string], undefined>,
  'updateCallerUserProfile' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [string], [] | [string]],
    undefined
  >,
  'updateReport' : ActorMethod<[string, LaporanUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];